trading:
  initial_balance: 10000
  max_position_size: 0.1
  slippage: 0.0005
  symbols:
  - BTC/USDT
  - ETH/USDT
  - XRP/USDT
  - SOLANA/USDT
  - BNB/USDT
  - DOGECOIN/USDT
  - TRON/USDT
  - POLKADOT/USDT
  - AVALANCHE/USDT
  - SHIBA/USDT
  timeframe: 5m
  transaction_cost: 0.001

environment:
  lookback_window: 50
  max_episode_steps: 1000
  normalize_observations: true
  reward_scaling: 1.0

ppo:
  batch_size: 64
  clip_range: 0.2
  ent_coef: 0.01
  gae_lambda: 0.95
  gamma: 0.99
  learning_rate: 0.0003
  max_grad_norm: 0.5
  n_epochs: 10
  n_steps: 2048
  vf_coef: 0.5

network:
  activation: tanh
  policy_layers:
  - 256
  - 256
  value_layers:
  - 256
  - 256

tradingview:
  provider: yfinance

indicators:
  bollinger_period: 20
  bollinger_std: 2
  ema_periods:
  - 12
  - 26
  macd_periods:
  - 12
  - 26
  - 9
  rsi_period: 14
  sma_periods:
  - 10
  - 20
  - 50

logging:
  level: INFO
  log_to_file: true
  use_tensorboard: true
  use_wandb: false

paths:
  data_dir: data
  log_dir: logs
  model_dir: models

training:
  eval_freq: 10000
  log_interval: 1000
  n_eval_episodes: 10
  save_freq: 50000
  total_timesteps: 1000000